---
name: "Autodiscovery - Default"

autodiscovery:
  groupby: all
  scmid: default
  actionid: default
  crawlers:
    helm:
      versionfilter:
        kind: semver

# Defines condition that must pass in order to update targets
conditions:
  dockerImage:
    name: 'Check that docker.io/victoriametrics/vmagent:{{ source "aoi" }} is published'
    kind: "dockerimage"
    spec:
      image: "docker.io/victoriametrics/vmagent"
      architecture: "amd64"


# Defines what needs to be udpated if needed
targets:
  imageTag:
    name: "Update victoriametrics/vmagent version in chart aoi"
    kind: "yaml"
    scmid: "helm-charts"
    spec:
      file: "charts/aoi.values.yaml"
      key: "$.prometheus.aoi.tag"

scms:
  default:
    kind: "github"
    spec:
      user: "{{ .github.default.user }}"
      email: "{{ .github.default.email }}"
      owner: "{{ .github.default.owner }}"
      repository: "{{ .github.default.repository }}"
      token: "{{ requiredEnv .github.default.token }}"
      username: "{{ .github.default.username }}"
      branch: "{{ .github.default.branch }}"

actions:
  default:
    kind: "github/pullrequest"
    scmid: "default"
    spec:
      title: Bump chart dependencies
      labels:
        - "dependencies"
        - "helm"
