---
name: "Autodiscovery - Default"

autodiscovery:
  groupby: all
  scmid: default
  actionid: default
  crawlers:
    helm:
      versionfilter:
        kind: semver

# Defines what needs to be udpated if needed
targets:
  imageTag:
    name: "Update victoriametrics/vmagent version in chart aoi"
    kind: "yaml"
    scmid: "default"
    spec:
      file: "charts/aoi/values.yaml"
      key: "$.promxy.image.tag"

scms:
  default:
    kind: "github"
    spec:
      user: "{{ .github.default.user }}"
      email: "{{ .github.default.email }}"
      owner: "{{ .github.default.owner }}"
      repository: "{{ .github.default.repository }}"
      token: "{{ requiredEnv .github.default.token }}"
      username: "{{ .github.default.username }}"
      branch: "{{ .github.default.branch }}"

actions:
  default:
    kind: "github/pullrequest"
    scmid: "default"
    spec:
      title: Bump chart dependencies
      labels:
        - "dependencies"
        - "helm"
