---
name: "Autodiscovery - Default"

autodiscovery:
  groupby: all
  scmid: default
  actionid: default
  crawlers:
    helm:
      versionfilter:
        kind: semver

scms:
  default:
    kind: "github"
    spec:
      user: "{{ .github.aoi.user }}"
      email: "{{ .github.aoi.email }}"
      owner: "{{ .github.aoi.owner }}"
      repository: "{{ .github.aoi.repository }}"
      token: '{{ requiredEnv .github.aoi.token }}'
      username: "{{ .github.aoi.username }}"
      branch: "{{ .github.aoi.branch }}"

actions:
  default:
    kind: "github/pullrequest"
    scmid: "default"
    spec:
      title: Bump chart dependencies
      labels:
        - "dependencies"
        - "helm"
