github:
  aoi:
    user: "Srams-Bertha"
    email: "srams@cyber-wizard.com"
    username: "UPDATECLI_GITHUB_ACTOR"
    token: "UPDATECLI_GITHUB_TOKEN"
    branch: "main"
    owner: "P3-Hype"
    repository: "github-actions-testing"
