apiVersion: v2
name: aoi
description: A Helm chart for Netic application operations infrastructure
type: application
version: 0.2.0
dependencies:
  - name: grafana
    version: 7.3.0
    repository: https://grafana.github.io/helm-charts
    condition: grafana.enabled
  - name: victoria-metrics-single
    alias: victoria-metrics-single-1
    version: 0.9.15
    repository: https://victoriametrics.github.io/helm-charts/
  - name: victoria-metrics-single
    alias: victoria-metrics-single-2
    version: 0.9.15
    repository: https://victoriametrics.github.io/helm-charts/
    condition: global.tsdb.high_availability.enabled
