name: Upgrade Helm charts minor versions
 
on:
  workflow_dispatch:


jobs:
 upgrade-helm-charts:
   runs-on: ubuntu-latest
   permissions: write-all
   steps:
     - name: Checkout
       uses: actions/checkout@v4
       with:
         fetch-depth: 0
 
     - name: Set up Helm
       uses: azure/setup-helm@v3
       with:
         version: v3.9.2
 
     - name: Set up Python
       uses: actions/setup-python@v5
       with:
         python-version: '3.10'
      
     - name: Install pyaml
       run: |
         pip3 install pyaml==23.12.0
 
     - name: Install updateCli
       run: |
         curl -sL -o /tmp/updatecli_amd64.deb https://github.com/updatecli/updatecli/releases/download/v0.72.0/updatecli_amd64.deb
         sudo apt install /tmp/updatecli_amd64.deb
 
     - name: Run chart bumper script
       run: |
         echo "$PWD"
         python .github/scripts/chart_bumper.py
         rm -f manifest.yaml

     - name: Set up Git
       run: |
         git config --global user.email "srams@cyber-wizard.com"
         git config --global user.name "Srams-Bertha"
         git config --global --add --bool push.autoSetupRemote true

     - name: Create Branch
       run: |
         helm_version=$(yq '.name' charts/aoi/Chart.yaml)-$(yq '.version' charts/aoi/Chart.yaml)
         branch=feature/upgrade-helm-charts-minors-$helm_version
         if git ls-remote | grep "$branch"; then
           echo Checkout existing branch $branch
           git checkout $branch
         else
           echo Create new branch $branch
           git checkout -b $branch
         fi
         echo "{HELM_BRANCH}={$branch}" >> $GITHUB_ENV

     - name: Commit and Push Changes
       run: |
         # - Update Helm charts
         git add .
         git commit -m "feat: upgrade helm charts"
         git push origin ${{ env.HELM_BRANCH }}
     
     - name: Create Pull Request
       run: |
         gh pr create --base main \
                      --head ${{ env.HELM_BRANCH }} \
                      --title "chore: upgrade helm charts minor versions" \
                      --body "Automatic upgrade of helm chart minor versions using https://github.com/updatecli/updatecli" \
                      --reviewer MathiasFM
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
