name: Upgrade helm charts minor versions
 
on:
  push:
    branches:
      - main


jobs:
 upgrade-helm-charts:
   runs-on: ubuntu-latest
   permissions: write-all
   steps:
     - name: Checkout
       uses: actions/checkout@v4
       with:
         fetch-depth: 0
 
     - name: Set up Helm
       uses: azure/setup-helm@v3
       with:
         version: v3.9.2
 
     - name: Set up Python
       uses: actions/setup-python@v5
       with:
         python-version: '3.10'
      
     - name: Install pyaml
       run: |
         pip3 install pyaml==23.12.0
 
     - name: Install updateCli
       run: |
         curl -sL -o /tmp/updatecli_amd64.deb https://github.com/updatecli/updatecli/releases/download/v0.72.0/updatecli_amd64.deb
         sudo apt install /tmp/updatecli_amd64.deb
 
     - name: Run chart bumper script
       run: |
         echo "$PWD"
         python .github/scripts/chart_bumper.py
         rm -f manifest.yaml

     - name: Set up Git
       run: |
         git config --global user.email "srams@cyber-wizard.com"
         git config --global user.name "Srams-Bertha"

     - name: Create Branch
       run: git checkout -b upgrade-helm-charts-minors

     - name: Commit and Push Changes
       run: |
         # Make your changes here, for example:
         # - Update Helm charts
         git commit -am "feat: upgrade helm charts"
         git push origin upgrade-helm-charts-minors
     
     - name: Create Pull Request
       run: |
         gh pr create --base main \
                       --head upgrade-helm-charts-minors \
                       --title "chore: upgrade helm charts minor versions" \
                       --body "Automatic upgrade of helm chart minor versions using https://github.com/updatecli/updatecli" \
                       --reviewer MathiasFM
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
