name: Renovate
on:
  workflow_dispatch:
  push:

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Renovate-dry-run
        uses: renovatebot/github-action@v40.0.3
        with:
          renovate-version: 37.175.3
          token: ${{ secrets.RENOVATE_TOKEN }}
        env:
          LOG_LEVEL: "debug"
          RENOVATE_AUTODISCOVER: "true"
