name: Renovate
on:
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Renovate-dry-run
        uses: renovatebot/github-action@2d90417499f45ff78a09586f7b9874b19817dba3 # v40.1.0
        with:
          renovate-version: 37.175.3
          token: ${{ secrets.RENOVATE_TOKEN }}
        env:
          LOG_LEVEL: "debug"
          RENOVATE_REPOSITORIES: "${{ github.repository }}"
          RENOVATE_AUTODISCOVER: "false"
          RENOVATE_ONBOARDING: "false"
