name: Upgrade Helm charts minor versions
 
on:
  workflow_dispatch:

permissions:
  contents: "write"
  pull-requests: "write"

jobs:
 upgrade-helm-charts:
   runs-on: ubuntu-latest
   env:
     HELM_REPO: aoi
   steps:
     - name: Checkout
       uses: actions/checkout@v4
       with:
         fetch-depth: 0
 
     - name: Set up Helm
       uses: azure/setup-helm@v3
       with:
         version: v3.9.2
 
     - name: Install Updatecli in the runner
       uses: updatecli/updatecli-action@v2
 
     - name: Check for updates to apply
       run: |
         "updatecli apply --config ./updatecli/updatecli.d --values ./updatecli/values.yaml"
         echo "${{ UPDATECLI_GITHUB_ACTOR }}"
       env:
         UPDATECLI_GITHUB_ACTOR: ${{ env.GITHUB_ACTOR }}
         UPDATECLI_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
